// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugtfatgzpclrmgjhitqm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndGZhdGd6cGNscm1namhpdHFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1MDgwMjgsImV4cCI6MjA2NzA4NDAyOH0.o2LFLmiePWa1n4AXUCXdxQcx5jhlnlzNEe0xMHrIGYI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});